import type { Logo, Category } from "./types"

export const categories: Category[] = [
  { id: "frontend", name: "Frontend" },
  { id: "backend", name: "Backend" },
  { id: "database", name: "Database" },
  { id: "devops", name: "DevOps" },
  { id: "design", name: "Design" },
  { id: "tools", name: "Tools" },
]

// export const logos: Logo[] = [
//   {
//     id: "react",
//     name: "React",
//     description: "A JavaScript library for building user interfaces",
//     svgUrl: "/logos/react.png",
//     category: "frontend",
//     tags: ["JavaScript", "Frontend", "Library", "UI"],
//     license: "MIT",
//     created: "2023-05-15T10:30:00Z",
//     updated: "2023-11-20T14:45:00Z",
//   },
//   {
//     id: "nextjs",
//     name: "Next.js",
//     description: "The React framework for production",
//     svgUrl: "/logos/nextjs.png",
//     category: "frontend",
//     tags: ["JavaScript", "React", "Framework", "SSR"],
//     license: "MIT",
//     created: "2023-05-15T10:30:00Z",
//     updated: "2023-11-20T14:45:00Z",
//   },
//   {
//     id: "typescript",
//     name: "TypeScript",
//     description: "A typed superset of JavaScript that compiles to plain JavaScript",
//     svgUrl: "/logos/typescript.png",
//     category: "frontend",
//     tags: ["JavaScript", "Language", "Static Typing"],
//     license: "Apache-2.0",
//     created: "2023-05-15T10:30:00Z",
//     updated: "2023-11-20T14:45:00Z",
//   },
//   {
//     id: "tailwindcss",
//     name: "Tailwind CSS",
//     description: "A utility-first CSS framework for rapid UI development",
//     svgUrl: "/logos/tailwindcss.png",
//     category: "frontend",
//     tags: ["CSS", "Framework", "Utility-First"],
//     license: "MIT",
//     created: "2023-05-15T10:30:00Z",
//     updated: "2023-11-20T14:45:00Z",
//   },
//   {
//     id: "nodejs",
//     name: "Node.js",
//     description: "JavaScript runtime built on Chrome's V8 JavaScript engine",
//     svgUrl: "/logos/nodejs.png",
//     category: "backend",
//     tags: ["JavaScript", "Runtime", "Backend"],
//     license: "MIT",
//     created: "2023-05-15T10:30:00Z",
//     updated: "2023-11-20T14:45:00Z",
//   },
//   {
//     id: "vercel",
//     name: "Vercel",
//     description: "Platform for frontend frameworks and static sites",
//     svgUrl: "/logos/vercel.png",
//     category: "devops",
//     tags: ["Hosting", "Deployment", "Platform"],
//     license: "Proprietary",
//     created: "2023-05-15T10:30:00Z",
//     updated: "2023-11-20T14:45:00Z",
//   },
//   {
//     id: "github",
//     name: "GitHub",
//     description: "Web-based platform for version control and collaboration",
//     svgUrl: "/logos/github.png",
//     category: "tools",
//     tags: ["Git", "Version Control", "Repository"],
//     license: "Proprietary",
//     created: "2023-05-15T10:30:00Z",
//     updated: "2023-11-20T14:45:00Z",
//   },
//   {
//     id: "vscode",
//     name: "VS Code",
//     description: "Code editor redefined and optimized for building modern web applications",
//     svgUrl: "/logos/vscode.png",
//     category: "tools",
//     tags: ["Editor", "IDE", "Microsoft"],
//     license: "MIT",
//     created: "2023-05-15T10:30:00Z",
//     updated: "2023-11-20T14:45:00Z",
//   },
//   {
//     id: "docker",
//     name: "Docker",
//     description: "Platform for developing, shipping, and running applications in containers",
//     svgUrl: "/logos/docker.png",
//     category: "devops",
//     tags: ["Container", "DevOps", "Deployment"],
//     license: "Apache-2.0",
//     created: "2023-05-15T10:30:00Z",
//     updated: "2023-11-20T14:45:00Z",
//   },
//   {
//     id: "graphql",
//     name: "GraphQL",
//     description: "A query language for your API",
//     svgUrl: "/logos/graphql.png",
//     category: "backend",
//     tags: ["API", "Query Language", "Data"],
//     license: "MIT",
//     created: "2023-05-15T10:30:00Z",
//     updated: "2023-11-20T14:45:00Z",
//   },
//   {
//     id: "mongodb",
//     name: "MongoDB",
//     description: "Document-oriented NoSQL database",
//     svgUrl: "/logos/mongodb.png",
//     category: "database",
//     tags: ["Database", "NoSQL", "Document"],
//     license: "SSPL",
//     created: "2023-05-15T10:30:00Z",
//     updated: "2023-11-20T14:45:00Z",
//   },
//   {
//     id: "postgresql",
//     name: "PostgreSQL",
//     description: "Powerful, open source object-relational database system",
//     svgUrl: "/logos/postgresql.png",
//     category: "database",
//     tags: ["Database", "SQL", "Relational"],
//     license: "PostgreSQL",
//     created: "2023-05-15T10:30:00Z",
//     updated: "2023-11-20T14:45:00Z",
//   },
//   {
//     id: "figma",
//     name: "Figma",
//     description: "Collaborative interface design tool",
//     svgUrl: "/logos/figma.svg",
//     category: "design",
//     tags: ["Design", "UI/UX", "Collaboration"],
//     license: "Proprietary",
//     created: "2023-05-15T10:30:00Z",
//     updated: "2023-11-20T14:45:00Z",
//   },
//   {
//     id: "aws",
//     name: "AWS",
//     description: "Cloud computing services by Amazon",
//     svgUrl: "/logos/aws.svg",
//     category: "devops",
//     tags: ["Cloud", "Hosting", "Services"],
//     license: "Proprietary",
//     created: "2023-05-15T10:30:00Z",
//     updated: "2023-11-20T14:45:00Z",
//   },
//   {
//     id: "firebase",
//     name: "Firebase",
//     description: "Google's mobile and web application development platform",
//     svgUrl: "/logos/firebase.svg",
//     category: "backend",
//     tags: ["Backend", "Database", "Authentication"],
//     license: "Proprietary",
//     created: "2023-05-15T10:30:00Z",
//     updated: "2023-11-20T14:45:00Z",
//   },
//   {
//     id: "vue",
//     name: "Vue.js",
//     description: "Progressive JavaScript framework for building UIs",
//     svgUrl: "/logos/vue.svg",
//     category: "frontend",
//     tags: ["JavaScript", "Framework", "UI"],
//     license: "MIT",
//     created: "2023-05-15T10:30:00Z",
//     updated: "2023-11-20T14:45:00Z",
//   },
// ]
